services:
    web:
        secrets:
            - Map__Tianditu__Key
            - Map__Tianditu__ServerKey

secrets:
    Map__Tianditu__Key:
        file: ${MARINE_INSIGHT_TIANDITU_SECRET_FILE:-./.secrets/tianditu_key}
    Map__Tianditu__ServerKey:
        file: ${MARINE_INSIGHT_TIANDITU_SERVER_SECRET_FILE:-./.secrets/tianditu_server_key}
