CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE TABLE audit_logs (
        "Id" uuid NOT NULL,
        "ActorUserId" uuid,
        "EventType" character varying(100) NOT NULL,
        "TargetType" character varying(100) NOT NULL,
        "TargetId" character varying(200),
        "Summary" character varying(1000) NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_audit_logs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE TABLE locations (
        id uuid NOT NULL,
        normalized_name character varying(160) NOT NULL,
        display_name character varying(200) NOT NULL,
        latitude numeric(9,6) NOT NULL,
        longitude numeric(9,6) NOT NULL,
        time_zone_id character varying(64) NOT NULL,
        location_type smallint NOT NULL,
        coast_orientation_deg numeric(6,2),
        is_preset boolean NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_locations" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE TABLE roles (
        "Id" uuid NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_roles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE TABLE users (
        "Id" uuid NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE TABLE forecast_batches (
        id uuid NOT NULL,
        location_id uuid NOT NULL,
        provider_code character varying(40) NOT NULL,
        data_domain smallint NOT NULL,
        endpoint_code character varying(60),
        model_code character varying(40),
        issued_at timestamp with time zone,
        fetched_at timestamp with time zone NOT NULL,
        range_start timestamp with time zone NOT NULL,
        range_end timestamp with time zone NOT NULL,
        quality_status smallint NOT NULL,
        freshness smallint NOT NULL,
        quality_flags integer NOT NULL,
        completeness double precision NOT NULL,
        requested_latitude numeric(9,6) NOT NULL,
        requested_longitude numeric(9,6) NOT NULL,
        grid_latitude numeric(9,6),
        grid_longitude numeric(9,6),
        raw_payload_hash character(64),
        CONSTRAINT "PK_forecast_batches" PRIMARY KEY (id),
        CONSTRAINT "FK_forecast_batches_locations_location_id" FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE TABLE role_claims (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_role_claims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_role_claims_roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES roles ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE TABLE favorite_locations (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "LocationId" uuid NOT NULL,
        "DefaultActivity" character varying(40),
        "Note" character varying(500),
        "SortOrder" integer NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_favorite_locations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_favorite_locations_locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES locations (id) ON DELETE CASCADE,
        CONSTRAINT "FK_favorite_locations_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE TABLE query_history (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "LocationId" uuid,
        "DisplayName" character varying(200) NOT NULL,
        "Latitude" double precision NOT NULL,
        "Longitude" double precision NOT NULL,
        "ForecastFromUtc" timestamp with time zone NOT NULL,
        "Hours" integer NOT NULL,
        "Activities" character varying(300) NOT NULL,
        "AnalysisId" uuid NOT NULL,
        "RiskLevel" character varying(30) NOT NULL,
        "Score" double precision,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_query_history" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_query_history_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE TABLE user_claims (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_user_claims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_user_claims_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE TABLE user_logins (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_user_logins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_user_logins_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE TABLE user_roles (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        CONSTRAINT "PK_user_roles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_user_roles_roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES roles ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_user_roles_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE TABLE user_settings (
        "UserId" uuid NOT NULL,
        "WindSpeedUnit" character varying(20) NOT NULL,
        "WaveHeightUnit" character varying(20) NOT NULL,
        "TemperatureUnit" character varying(20) NOT NULL,
        "DefaultActivity" character varying(40),
        "TimeZoneId" character varying(100),
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_user_settings" PRIMARY KEY ("UserId"),
        CONSTRAINT "FK_user_settings_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE TABLE user_tokens (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_user_tokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_user_tokens_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE TABLE forecast_points (
        id uuid NOT NULL,
        batch_id uuid NOT NULL,
        forecast_time timestamp with time zone NOT NULL,
        wind_speed_ms double precision,
        wind_gust_ms double precision,
        wind_direction_deg double precision,
        temperature_c double precision,
        humidity_percent double precision,
        pressure_hpa double precision,
        cloud_cover_percent double precision,
        precipitation_mm double precision,
        cape_jkg double precision,
        visibility_m double precision,
        weather_code integer,
        thunderstorm boolean,
        wave_height_m double precision,
        wave_period_s double precision,
        wave_peak_period_s double precision,
        wave_direction_deg double precision,
        wind_wave_height_m double precision,
        wind_wave_period_s double precision,
        wind_wave_peak_period_s double precision,
        wind_wave_direction_deg double precision,
        swell_height_m double precision,
        swell_period_s double precision,
        swell_peak_period_s double precision,
        swell_direction_deg double precision,
        sea_temperature_c double precision,
        current_speed_ms double precision,
        current_direction_deg double precision,
        tide_height_m double precision,
        tide_type smallint,
        quality_status smallint NOT NULL,
        freshness smallint NOT NULL,
        missing_mask bigint NOT NULL,
        quality_flags integer NOT NULL,
        completeness double precision NOT NULL,
        CONSTRAINT "PK_forecast_points" PRIMARY KEY (id),
        CONSTRAINT "FK_forecast_points_forecast_batches_batch_id" FOREIGN KEY (batch_id) REFERENCES forecast_batches (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE TABLE forecast_point_sources (
        forecast_point_id uuid NOT NULL,
        metric smallint NOT NULL,
        provider_code character varying(40) NOT NULL,
        source_model character varying(80) NOT NULL,
        batch_id uuid NOT NULL,
        forecast_time timestamp with time zone NOT NULL,
        quality_status smallint NOT NULL,
        freshness smallint NOT NULL,
        quality_flags integer NOT NULL,
        CONSTRAINT "PK_forecast_point_sources" PRIMARY KEY (forecast_point_id, metric),
        CONSTRAINT "FK_forecast_point_sources_forecast_points_forecast_point_id" FOREIGN KEY (forecast_point_id) REFERENCES forecast_points (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    INSERT INTO locations (id, coast_orientation_deg, created_at, display_name, is_preset, latitude, location_type, longitude, normalized_name, time_zone_id)
    VALUES ('70cfb8c4-7af7-4c43-8f38-9a27e7cc2de7', NULL, TIMESTAMPTZ '2026-01-01T00:00:00+00:00', '嵊泗列岛', TRUE, 30.727, 1, 122.451, '嵊泗列岛', 'Asia/Shanghai');
    INSERT INTO locations (id, coast_orientation_deg, created_at, display_name, is_preset, latitude, location_type, longitude, normalized_name, time_zone_id)
    VALUES ('8a477d67-73fa-4f43-b954-cd29d238a89d', NULL, TIMESTAMPTZ '2026-01-01T00:00:00+00:00', '东极岛', TRUE, 30.194, 1, 122.687, '东极岛', 'Asia/Shanghai');
    INSERT INTO locations (id, coast_orientation_deg, created_at, display_name, is_preset, latitude, location_type, longitude, normalized_name, time_zone_id)
    VALUES ('d6ac8e90-44ae-4d1f-88b9-8b73db7af6a1', NULL, TIMESTAMPTZ '2026-01-01T00:00:00+00:00', '普陀山', TRUE, 30.01, 1, 122.388, '普陀山', 'Asia/Shanghai');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE INDEX "IX_audit_logs_ActorUserId_CreatedAtUtc" ON audit_logs ("ActorUserId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE INDEX "IX_audit_logs_CreatedAtUtc" ON audit_logs ("CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE INDEX "IX_favorite_locations_LocationId" ON favorite_locations ("LocationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE UNIQUE INDEX "IX_favorite_locations_UserId_LocationId" ON favorite_locations ("UserId", "LocationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE INDEX "IX_favorite_locations_UserId_SortOrder" ON favorite_locations ("UserId", "SortOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE INDEX "IX_forecast_batches_location_id_fetched_at" ON forecast_batches (location_id, fetched_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE UNIQUE INDEX "IX_forecast_batches_provider_code_data_domain_model_code_locat~" ON forecast_batches (provider_code, data_domain, model_code, location_id, issued_at, range_start);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE UNIQUE INDEX "IX_forecast_points_batch_id_forecast_time" ON forecast_points (batch_id, forecast_time);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE UNIQUE INDEX "IX_locations_normalized_name_latitude_longitude" ON locations (normalized_name, latitude, longitude);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE INDEX "IX_query_history_UserId_CreatedAtUtc" ON query_history ("UserId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE INDEX "IX_role_claims_RoleId" ON role_claims ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON roles ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE INDEX "IX_user_claims_UserId" ON user_claims ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE INDEX "IX_user_logins_UserId" ON user_logins ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE INDEX "IX_user_roles_RoleId" ON user_roles ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE INDEX "EmailIndex" ON users ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON users ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260813025010_InitialPostgreSql') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260813025010_InitialPostgreSql', '10.0.11');
    END IF;
END $EF$;
COMMIT;

