// <auto-generated />
using System;
using MarineInsight.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarineInsight.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MarineInsightDbContext))]
    [Migration("20260715095814_InitialForecastStorage")]
    partial class InitialForecastStorage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.ForecastBatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<double>("Completeness")
                        .HasColumnType("REAL")
                        .HasColumnName("completeness");

                    b.Property<short>("DataDomain")
                        .HasColumnType("INTEGER")
                        .HasColumnName("data_domain");

                    b.Property<string>("EndpointCode")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("endpoint_code");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("fetched_at");

                    b.Property<short>("Freshness")
                        .HasColumnType("INTEGER")
                        .HasColumnName("freshness");

                    b.Property<decimal?>("GridLatitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("grid_latitude");

                    b.Property<decimal?>("GridLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("grid_longitude");

                    b.Property<DateTimeOffset?>("IssuedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("location_id");

                    b.Property<string>("ModelCode")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("model_code");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_code");

                    b.Property<int>("QualityFlags")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quality_flags");

                    b.Property<short>("QualityStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quality_status");

                    b.Property<DateTimeOffset>("RangeEndUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("range_end");

                    b.Property<DateTimeOffset>("RangeStartUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("range_start");

                    b.Property<string>("RawPayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_payload_hash")
                        .IsFixedLength();

                    b.Property<decimal>("RequestedLatitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("requested_latitude");

                    b.Property<decimal>("RequestedLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("requested_longitude");

                    b.HasKey("Id");

                    b.HasIndex("LocationId", "FetchedAtUtc");

                    b.HasIndex("ProviderCode", "DataDomain", "ModelCode", "LocationId", "IssuedAtUtc", "RangeStartUtc")
                        .IsUnique();

                    b.ToTable("forecast_batches", (string)null);
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.ForecastPointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("TEXT")
                        .HasColumnName("batch_id");

                    b.Property<double?>("CapeJkg")
                        .HasColumnType("REAL")
                        .HasColumnName("cape_jkg");

                    b.Property<double?>("CloudCoverPct")
                        .HasColumnType("REAL")
                        .HasColumnName("cloud_cover_percent");

                    b.Property<double>("Completeness")
                        .HasColumnType("REAL")
                        .HasColumnName("completeness");

                    b.Property<double?>("CurrentDirectionDeg")
                        .HasColumnType("REAL")
                        .HasColumnName("current_direction_deg");

                    b.Property<double?>("CurrentSpeedMs")
                        .HasColumnType("REAL")
                        .HasColumnName("current_speed_ms");

                    b.Property<DateTimeOffset>("ForecastTimeUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("forecast_time");

                    b.Property<short>("Freshness")
                        .HasColumnType("INTEGER")
                        .HasColumnName("freshness");

                    b.Property<long>("MissingMetricsMask")
                        .HasColumnType("INTEGER")
                        .HasColumnName("missing_mask");

                    b.Property<double?>("PrecipitationMmPerHour")
                        .HasColumnType("REAL")
                        .HasColumnName("precipitation_mm");

                    b.Property<int>("QualityFlags")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quality_flags");

                    b.Property<short>("QualityStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quality_status");

                    b.Property<double?>("RelativeHumidityPct")
                        .HasColumnType("REAL")
                        .HasColumnName("humidity_percent");

                    b.Property<double?>("SeaTemperatureC")
                        .HasColumnType("REAL")
                        .HasColumnName("sea_temperature_c");

                    b.Property<double?>("SurfacePressureHpa")
                        .HasColumnType("REAL")
                        .HasColumnName("pressure_hpa");

                    b.Property<double?>("SwellDirectionDeg")
                        .HasColumnType("REAL")
                        .HasColumnName("swell_direction_deg");

                    b.Property<double?>("SwellHeightM")
                        .HasColumnType("REAL")
                        .HasColumnName("swell_height_m");

                    b.Property<double?>("SwellPeakPeriodS")
                        .HasColumnType("REAL")
                        .HasColumnName("swell_peak_period_s");

                    b.Property<double?>("SwellPeriodS")
                        .HasColumnType("REAL")
                        .HasColumnName("swell_period_s");

                    b.Property<double?>("TemperatureC")
                        .HasColumnType("REAL")
                        .HasColumnName("temperature_c");

                    b.Property<bool?>("Thunderstorm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("thunderstorm");

                    b.Property<double?>("TideHeightM")
                        .HasColumnType("REAL")
                        .HasColumnName("tide_height_m");

                    b.Property<short?>("TideType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tide_type");

                    b.Property<double?>("VisibilityM")
                        .HasColumnType("REAL")
                        .HasColumnName("visibility_m");

                    b.Property<double?>("WaveDirectionDeg")
                        .HasColumnType("REAL")
                        .HasColumnName("wave_direction_deg");

                    b.Property<double?>("WaveHeightM")
                        .HasColumnType("REAL")
                        .HasColumnName("wave_height_m");

                    b.Property<double?>("WavePeakPeriodS")
                        .HasColumnType("REAL")
                        .HasColumnName("wave_peak_period_s");

                    b.Property<double?>("WavePeriodS")
                        .HasColumnType("REAL")
                        .HasColumnName("wave_period_s");

                    b.Property<int?>("WeatherCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weather_code");

                    b.Property<double?>("WindDirectionDeg")
                        .HasColumnType("REAL")
                        .HasColumnName("wind_direction_deg");

                    b.Property<double?>("WindGustMs")
                        .HasColumnType("REAL")
                        .HasColumnName("wind_gust_ms");

                    b.Property<double?>("WindSpeedMs")
                        .HasColumnType("REAL")
                        .HasColumnName("wind_speed_ms");

                    b.Property<double?>("WindWaveDirectionDeg")
                        .HasColumnType("REAL")
                        .HasColumnName("wind_wave_direction_deg");

                    b.Property<double?>("WindWaveHeightM")
                        .HasColumnType("REAL")
                        .HasColumnName("wind_wave_height_m");

                    b.Property<double?>("WindWavePeakPeriodS")
                        .HasColumnType("REAL")
                        .HasColumnName("wind_wave_peak_period_s");

                    b.Property<double?>("WindWavePeriodS")
                        .HasColumnType("REAL")
                        .HasColumnName("wind_wave_period_s");

                    b.HasKey("Id");

                    b.HasIndex("BatchId", "ForecastTimeUtc")
                        .IsUnique();

                    b.ToTable("forecast_points", (string)null);
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.ForecastPointSourceEntity", b =>
                {
                    b.Property<Guid>("ForecastPointId")
                        .HasColumnType("TEXT")
                        .HasColumnName("forecast_point_id");

                    b.Property<short>("Metric")
                        .HasColumnType("INTEGER")
                        .HasColumnName("metric");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("TEXT")
                        .HasColumnName("batch_id");

                    b.Property<DateTimeOffset>("ForecastTimeUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("forecast_time");

                    b.Property<short>("Freshness")
                        .HasColumnType("INTEGER")
                        .HasColumnName("freshness");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_code");

                    b.Property<int>("QualityFlags")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quality_flags");

                    b.Property<short>("QualityStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quality_status");

                    b.Property<string>("SourceModel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_model");

                    b.HasKey("ForecastPointId", "Metric");

                    b.ToTable("forecast_point_sources", (string)null);
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.LocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<decimal?>("CoastOrientationDeg")
                        .HasPrecision(6, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("coast_orientation_deg");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsPreset")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_preset");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("latitude");

                    b.Property<short>("LocationType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("location_type");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("longitude");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_name");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName", "Latitude", "Longitude")
                        .IsUnique();

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.ForecastBatchEntity", b =>
                {
                    b.HasOne("MarineInsight.Infrastructure.Persistence.Entities.LocationEntity", "Location")
                        .WithMany("ForecastBatches")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.ForecastPointEntity", b =>
                {
                    b.HasOne("MarineInsight.Infrastructure.Persistence.Entities.ForecastBatchEntity", "Batch")
                        .WithMany("Points")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.ForecastPointSourceEntity", b =>
                {
                    b.HasOne("MarineInsight.Infrastructure.Persistence.Entities.ForecastPointEntity", "ForecastPoint")
                        .WithMany("Sources")
                        .HasForeignKey("ForecastPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ForecastPoint");
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.ForecastBatchEntity", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.ForecastPointEntity", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.LocationEntity", b =>
                {
                    b.Navigation("ForecastBatches");
                });
#pragma warning restore 612, 618
        }
    }
}
