// <auto-generated />
using System;
using MarineInsight.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarineInsight.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MarineInsightDbContext))]
    [Migration("20260820104531_AddProviderCredentials")]
    partial class AddProviderCredentials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.AnalysisReportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<short?>("ActivityType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activity_type");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("algorithm_version");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("Hours")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hours");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("location_id");

                    b.Property<DateTimeOffset>("RangeEndUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("range_end");

                    b.Property<DateTimeOffset>("RangeStartUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("range_start");

                    b.Property<DateTimeOffset?>("RecommendedEndUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("recommended_end");

                    b.Property<DateTimeOffset?>("RecommendedStartUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("recommended_start");

                    b.Property<DateTimeOffset?>("ReturnBeforeUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("return_before");

                    b.Property<short>("RiskLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("risk_level");

                    b.Property<double?>("Score")
                        .HasColumnType("REAL")
                        .HasColumnName("score");

                    b.Property<string>("SourceSetHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_set_hash");

                    b.Property<string>("SummaryTemplateCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("summary_template_code");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceSetHash");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("analysis_results", (string)null);
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.AnalysisRiskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<double?>("Actual")
                        .HasColumnType("REAL")
                        .HasColumnName("actual");

                    b.Property<Guid>("AnalysisResultId")
                        .HasColumnType("TEXT")
                        .HasColumnName("analysis_result_id");

                    b.Property<DateTimeOffset>("ForecastTimeUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("forecast_time");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<double>("Penalty")
                        .HasColumnType("REAL")
                        .HasColumnName("penalty");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("rule_code");

                    b.Property<short>("Severity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("severity");

                    b.Property<double?>("Threshold")
                        .HasColumnType("REAL")
                        .HasColumnName("threshold");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisResultId", "Severity");

                    b.ToTable("analysis_risks", (string)null);
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.AnalysisSourceBatchEntity", b =>
                {
                    b.Property<Guid>("AnalysisResultId")
                        .HasColumnType("TEXT")
                        .HasColumnName("analysis_result_id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("TEXT")
                        .HasColumnName("batch_id");

                    b.Property<short>("SourceRole")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_role");

                    b.Property<short>("DataDomain")
                        .HasColumnType("INTEGER")
                        .HasColumnName("data_domain");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_code");

                    b.Property<string>("SelectionPolicy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("selection_policy");

                    b.Property<string>("SourceModel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_model");

                    b.HasKey("AnalysisResultId", "BatchId", "SourceRole");

                    b.ToTable("analysis_source_batches", (string)null);
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.AuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("ActorUserId", "CreatedAtUtc");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.FavoriteLocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultActivity")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId", "LocationId")
                        .IsUnique();

                    b.HasIndex("UserId", "SortOrder");

                    b.ToTable("favorite_locations", (string)null);
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.ForecastBatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<double>("Completeness")
                        .HasColumnType("REAL")
                        .HasColumnName("completeness");

                    b.Property<short>("DataDomain")
                        .HasColumnType("INTEGER")
                        .HasColumnName("data_domain");

                    b.Property<string>("EndpointCode")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("endpoint_code");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("fetched_at");

                    b.Property<short>("Freshness")
                        .HasColumnType("INTEGER")
                        .HasColumnName("freshness");

                    b.Property<decimal?>("GridLatitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("grid_latitude");

                    b.Property<decimal?>("GridLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("grid_longitude");

                    b.Property<DateTimeOffset?>("IssuedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("location_id");

                    b.Property<string>("ModelCode")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("model_code");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_code");

                    b.Property<int>("QualityFlags")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quality_flags");

                    b.Property<short>("QualityStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quality_status");

                    b.Property<DateTimeOffset>("RangeEndUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("range_end");

                    b.Property<DateTimeOffset>("RangeStartUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("range_start");

                    b.Property<string>("RawPayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_payload_hash")
                        .IsFixedLength();

                    b.Property<decimal>("RequestedLatitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("requested_latitude");

                    b.Property<decimal>("RequestedLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("requested_longitude");

                    b.HasKey("Id");

                    b.HasIndex("LocationId", "FetchedAtUtc");

                    b.HasIndex("ProviderCode", "DataDomain", "ModelCode", "LocationId", "IssuedAtUtc", "RangeStartUtc")
                        .IsUnique();

                    b.ToTable("forecast_batches", (string)null);
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.ForecastPointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("TEXT")
                        .HasColumnName("batch_id");

                    b.Property<double?>("CapeJkg")
                        .HasColumnType("REAL")
                        .HasColumnName("cape_jkg");

                    b.Property<double?>("CloudCoverPct")
                        .HasColumnType("REAL")
                        .HasColumnName("cloud_cover_percent");

                    b.Property<double>("Completeness")
                        .HasColumnType("REAL")
                        .HasColumnName("completeness");

                    b.Property<double?>("CurrentDirectionDeg")
                        .HasColumnType("REAL")
                        .HasColumnName("current_direction_deg");

                    b.Property<double?>("CurrentSpeedMs")
                        .HasColumnType("REAL")
                        .HasColumnName("current_speed_ms");

                    b.Property<DateTimeOffset>("ForecastTimeUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("forecast_time");

                    b.Property<short>("Freshness")
                        .HasColumnType("INTEGER")
                        .HasColumnName("freshness");

                    b.Property<long>("MissingMetricsMask")
                        .HasColumnType("INTEGER")
                        .HasColumnName("missing_mask");

                    b.Property<double?>("PrecipitationMmPerHour")
                        .HasColumnType("REAL")
                        .HasColumnName("precipitation_mm");

                    b.Property<int>("QualityFlags")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quality_flags");

                    b.Property<short>("QualityStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quality_status");

                    b.Property<double?>("RelativeHumidityPct")
                        .HasColumnType("REAL")
                        .HasColumnName("humidity_percent");

                    b.Property<double?>("SeaTemperatureC")
                        .HasColumnType("REAL")
                        .HasColumnName("sea_temperature_c");

                    b.Property<double?>("SurfacePressureHpa")
                        .HasColumnType("REAL")
                        .HasColumnName("pressure_hpa");

                    b.Property<double?>("SwellDirectionDeg")
                        .HasColumnType("REAL")
                        .HasColumnName("swell_direction_deg");

                    b.Property<double?>("SwellHeightM")
                        .HasColumnType("REAL")
                        .HasColumnName("swell_height_m");

                    b.Property<double?>("SwellPeakPeriodS")
                        .HasColumnType("REAL")
                        .HasColumnName("swell_peak_period_s");

                    b.Property<double?>("SwellPeriodS")
                        .HasColumnType("REAL")
                        .HasColumnName("swell_period_s");

                    b.Property<double?>("TemperatureC")
                        .HasColumnType("REAL")
                        .HasColumnName("temperature_c");

                    b.Property<bool?>("Thunderstorm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("thunderstorm");

                    b.Property<double?>("TideHeightM")
                        .HasColumnType("REAL")
                        .HasColumnName("tide_height_m");

                    b.Property<short?>("TideType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tide_type");

                    b.Property<double?>("VisibilityM")
                        .HasColumnType("REAL")
                        .HasColumnName("visibility_m");

                    b.Property<double?>("WaveDirectionDeg")
                        .HasColumnType("REAL")
                        .HasColumnName("wave_direction_deg");

                    b.Property<double?>("WaveHeightM")
                        .HasColumnType("REAL")
                        .HasColumnName("wave_height_m");

                    b.Property<double?>("WavePeakPeriodS")
                        .HasColumnType("REAL")
                        .HasColumnName("wave_peak_period_s");

                    b.Property<double?>("WavePeriodS")
                        .HasColumnType("REAL")
                        .HasColumnName("wave_period_s");

                    b.Property<int?>("WeatherCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weather_code");

                    b.Property<double?>("WindDirectionDeg")
                        .HasColumnType("REAL")
                        .HasColumnName("wind_direction_deg");

                    b.Property<double?>("WindGustMs")
                        .HasColumnType("REAL")
                        .HasColumnName("wind_gust_ms");

                    b.Property<double?>("WindSpeedMs")
                        .HasColumnType("REAL")
                        .HasColumnName("wind_speed_ms");

                    b.Property<double?>("WindWaveDirectionDeg")
                        .HasColumnType("REAL")
                        .HasColumnName("wind_wave_direction_deg");

                    b.Property<double?>("WindWaveHeightM")
                        .HasColumnType("REAL")
                        .HasColumnName("wind_wave_height_m");

                    b.Property<double?>("WindWavePeakPeriodS")
                        .HasColumnType("REAL")
                        .HasColumnName("wind_wave_peak_period_s");

                    b.Property<double?>("WindWavePeriodS")
                        .HasColumnType("REAL")
                        .HasColumnName("wind_wave_period_s");

                    b.HasKey("Id");

                    b.HasIndex("BatchId", "ForecastTimeUtc")
                        .IsUnique();

                    b.ToTable("forecast_points", (string)null);
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.ForecastPointSourceEntity", b =>
                {
                    b.Property<Guid>("ForecastPointId")
                        .HasColumnType("TEXT")
                        .HasColumnName("forecast_point_id");

                    b.Property<short>("Metric")
                        .HasColumnType("INTEGER")
                        .HasColumnName("metric");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("TEXT")
                        .HasColumnName("batch_id");

                    b.Property<DateTimeOffset>("ForecastTimeUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("forecast_time");

                    b.Property<short>("Freshness")
                        .HasColumnType("INTEGER")
                        .HasColumnName("freshness");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_code");

                    b.Property<int>("QualityFlags")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quality_flags");

                    b.Property<short>("QualityStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quality_status");

                    b.Property<string>("SourceModel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_model");

                    b.HasKey("ForecastPointId", "Metric");

                    b.ToTable("forecast_point_sources", (string)null);
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.LocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<decimal?>("CoastOrientationDeg")
                        .HasPrecision(6, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("coast_orientation_deg");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsHomeDefault")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_home_default");

                    b.Property<bool>("IsPreset")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_preset");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("latitude");

                    b.Property<short>("LocationType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("location_type");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("longitude");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_name");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName", "Latitude", "Longitude")
                        .IsUnique();

                    b.ToTable("locations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a477d67-73fa-4f43-b954-cd29d238a89d"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "东极岛",
                            IsHomeDefault = false,
                            IsPreset = true,
                            Latitude = 30.200m,
                            LocationType = (short)1,
                            Longitude = 122.680m,
                            NormalizedName = "东极岛",
                            TimeZoneId = "Asia/Shanghai"
                        },
                        new
                        {
                            Id = new Guid("70cfb8c4-7af7-4c43-8f38-9a27e7cc2de7"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "嵊泗列岛",
                            IsHomeDefault = false,
                            IsPreset = true,
                            Latitude = 30.727m,
                            LocationType = (short)1,
                            Longitude = 122.451m,
                            NormalizedName = "嵊泗列岛",
                            TimeZoneId = "Asia/Shanghai"
                        },
                        new
                        {
                            Id = new Guid("d6ac8e90-44ae-4d1f-88b9-8b73db7af6a1"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "普陀山",
                            IsHomeDefault = false,
                            IsPreset = true,
                            Latitude = 30.010m,
                            LocationType = (short)1,
                            Longitude = 122.388m,
                            NormalizedName = "普陀山",
                            TimeZoneId = "Asia/Shanghai"
                        },
                        new
                        {
                            Id = new Guid("9b2c4d6e-8f1a-4b7c-9d3e-5f0a2c4b6d8e"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "岱山岛",
                            IsHomeDefault = false,
                            IsPreset = true,
                            Latitude = 30.288m,
                            LocationType = (short)1,
                            Longitude = 122.165m,
                            NormalizedName = "岱山岛",
                            TimeZoneId = "Asia/Shanghai"
                        });
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.ProviderCredentialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("CreditWarning")
                        .HasColumnType("INTEGER")
                        .HasColumnName("credit_warning");

                    b.Property<string>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("encrypted_value");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("health");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("KeyHint")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("key_hint");

                    b.Property<DateTimeOffset?>("LastCheckedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_checked_at");

                    b.Property<string>("LastFailureReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_failure_reason");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_name");

                    b.Property<int?>("RemainingCredits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("remaining_credits");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProviderName")
                        .IsUnique()
                        .HasFilter("\"is_active\"");

                    b.HasIndex("ProviderName", "KeyHint")
                        .IsUnique();

                    b.ToTable("provider_credentials", (string)null);
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.QueryHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Activities")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ForecastFromUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Hours")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Score")
                        .HasColumnType("REAL");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("query_history", (string)null);
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.UserLocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultActivity")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SortOrder");

                    b.ToTable("user_locations", (string)null);
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.UserSettingEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultActivity")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("TemperatureUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WaveHeightUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("WindSpeedUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.MarineInsightUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.AnalysisReportEntity", b =>
                {
                    b.HasOne("MarineInsight.Infrastructure.Persistence.MarineInsightUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.AnalysisRiskEntity", b =>
                {
                    b.HasOne("MarineInsight.Infrastructure.Persistence.Entities.AnalysisReportEntity", "AnalysisResult")
                        .WithMany("Risks")
                        .HasForeignKey("AnalysisResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisResult");
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.AnalysisSourceBatchEntity", b =>
                {
                    b.HasOne("MarineInsight.Infrastructure.Persistence.Entities.AnalysisReportEntity", "AnalysisResult")
                        .WithMany("SourceBatches")
                        .HasForeignKey("AnalysisResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisResult");
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.FavoriteLocationEntity", b =>
                {
                    b.HasOne("MarineInsight.Infrastructure.Persistence.Entities.LocationEntity", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MarineInsight.Infrastructure.Persistence.MarineInsightUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.ForecastBatchEntity", b =>
                {
                    b.HasOne("MarineInsight.Infrastructure.Persistence.Entities.LocationEntity", "Location")
                        .WithMany("ForecastBatches")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.ForecastPointEntity", b =>
                {
                    b.HasOne("MarineInsight.Infrastructure.Persistence.Entities.ForecastBatchEntity", "Batch")
                        .WithMany("Points")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.ForecastPointSourceEntity", b =>
                {
                    b.HasOne("MarineInsight.Infrastructure.Persistence.Entities.ForecastPointEntity", "ForecastPoint")
                        .WithMany("Sources")
                        .HasForeignKey("ForecastPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ForecastPoint");
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.QueryHistoryEntity", b =>
                {
                    b.HasOne("MarineInsight.Infrastructure.Persistence.MarineInsightUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.UserLocationEntity", b =>
                {
                    b.HasOne("MarineInsight.Infrastructure.Persistence.MarineInsightUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.UserSettingEntity", b =>
                {
                    b.HasOne("MarineInsight.Infrastructure.Persistence.MarineInsightUser", null)
                        .WithOne()
                        .HasForeignKey("MarineInsight.Infrastructure.Persistence.Entities.UserSettingEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MarineInsight.Infrastructure.Persistence.MarineInsightUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MarineInsight.Infrastructure.Persistence.MarineInsightUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarineInsight.Infrastructure.Persistence.MarineInsightUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MarineInsight.Infrastructure.Persistence.MarineInsightUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.AnalysisReportEntity", b =>
                {
                    b.Navigation("Risks");

                    b.Navigation("SourceBatches");
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.ForecastBatchEntity", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.ForecastPointEntity", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("MarineInsight.Infrastructure.Persistence.Entities.LocationEntity", b =>
                {
                    b.Navigation("ForecastBatches");
                });
#pragma warning restore 612, 618
        }
    }
}
